### ISSUE TITLE
Safari doesn’t support .ogg

### ISSUE THREAD

**Issue by SaltyAom** [rayriffy/miko#1]
Safari doesn't support audio format `.ogg`. Result, no sound play on both iOS Safari and MacOS.

Based on [caniuse.com](https://caniuse.com/#search=Ogg)
![image](https://user-images.githubusercontent.com/35027979/87226101-d8186700-c3bb-11ea-893c-4c5bafe43702.jpeg)

Changing format to `.mp4` would be working.

**Comment by rayriffy** [comment]
What about MP3 Audio Format? Does it gonna work? Audacity does not have an option to export into MP4, may need some workaround to do an MP4

**Comment by SaltyAom** [comment]
Yeah mp3 work.
Remember [pat senko](https://pat-senko.now.sh)? That use mp3 and it worked.
Btw, I can convert the ogg to mp3. I'll make a PR then.

**Comment by rayriffy** [comment]
If you wish to.

**Comment by SaltyAom** [comment]
#2 it's worked. But iOS Safari really lack of Safari support. I do as best as I could.

**Comment by rayriffy** [comment]
#2 is merged. Thanks for your contribution comrades!

![gif-comrades](https://user-images.githubusercontent.com/22584594/87267107-c214be80-c501-11ea-8f7b-57040d59ddcd.gif)
